// Generated by tools/edgeone/chunk-large.mjs. No credentials.
export default {
  "mrp-files/tommao.mrp": {
    "version": 1,
    "size": 3942799,
    "md5": "1aec07488b268c46291b0945792b77e4",
    "sha256": "eb09acb556cc601bd3e3b54cdffb5d2abe9bff319ed323242939f102f8e725a7",
    "parts": [
      {
        "key": "chunks/eb09acb556cc601bd3e3b54cdffb5d2abe9bff319ed323242939f102f8e725a7/0",
        "size": 1900000,
        "md5": "8b91e074324df98086fc2c9f6d7e41b4",
        "sha256": "d2e8959877d28f7ab418559c1b2893f4eeae0aef3ffcfd146ffbdc50d1967eac"
      },
      {
        "key": "chunks/eb09acb556cc601bd3e3b54cdffb5d2abe9bff319ed323242939f102f8e725a7/1",
        "size": 1900000,
        "md5": "01509797a9a1568bb8c4974fe7d24b07",
        "sha256": "2b78decd64b56d3c94625f6b4c251ab1873cd14dd8502e2d8c3d07e6121137a0"
      },
      {
        "key": "chunks/eb09acb556cc601bd3e3b54cdffb5d2abe9bff319ed323242939f102f8e725a7/2",
        "size": 142799,
        "md5": "2620ded870332e472abb594602d4dc23",
        "sha256": "10d5d06521209657c234a176e73a32babe451e687a80cbfa8f9e008c3893789a"
      }
    ]
  },
  "mrp-files/395020_240320_gjmrry.mrp": {
    "version": 1,
    "size": 2318296,
    "md5": "df8ed715de1c36384121b2e7ad42002e",
    "sha256": "70745a80f2a1eb064fbf5a0e8014b2b744f38e6e3220718570a42ca380dd8527",
    "parts": [
      {
        "key": "chunks/70745a80f2a1eb064fbf5a0e8014b2b744f38e6e3220718570a42ca380dd8527/0",
        "size": 1900000,
        "md5": "7c4b04cba6172bb3c05bb6fbdfdc3846",
        "sha256": "2ab5e98ce6d524e5353aebb3e1be875a0f498b26cc633fe3f4f7135c917b471b"
      },
      {
        "key": "chunks/70745a80f2a1eb064fbf5a0e8014b2b744f38e6e3220718570a42ca380dd8527/1",
        "size": 418296,
        "md5": "88cdeabcceba93867fbf84c189ef705a",
        "sha256": "142e533ad434086dbbaf7fc3e8e9fcfcc4f8c05bd00363eea1c391dd2f9864aa"
      }
    ]
  },
  "mrp-files/talkcat.zip": {
    "version": 1,
    "size": 3481569,
    "md5": "874f1ed2c69d8324d27e0559ec309675",
    "sha256": "90f7fcb0d4d5fa3078b0ad345cea67d6cf9872bd1ab33d4bfe47dc42e05f425f",
    "parts": [
      {
        "key": "chunks/90f7fcb0d4d5fa3078b0ad345cea67d6cf9872bd1ab33d4bfe47dc42e05f425f/0",
        "size": 1900000,
        "md5": "065890cf3a89fda19e0c474f2a9b316f",
        "sha256": "02812d65a1f62d150b2ec9281ecf35904d5ad54fd91a5804c00741aca07987ab"
      },
      {
        "key": "chunks/90f7fcb0d4d5fa3078b0ad345cea67d6cf9872bd1ab33d4bfe47dc42e05f425f/1",
        "size": 1581569,
        "md5": "144fae67f1915bd05ee39acbeed90cd9",
        "sha256": "81c1eafd0c498def54c393808eec76314ebbfdac472c96e2d0bf027faa4e8ceb"
      }
    ]
  },
  "runtime/mythroad_res/ghdtz/resourcefile.res": {
    "version": 1,
    "size": 3165754,
    "md5": "07145bfe961008e22f48fbba6325420e",
    "sha256": "0d6da06323f18e5d6eb6db9124a982701d10c8620b176ef1afb3f2c159722167",
    "parts": [
      {
        "key": "chunks/0d6da06323f18e5d6eb6db9124a982701d10c8620b176ef1afb3f2c159722167/0",
        "size": 1900000,
        "md5": "5af1dc8fe90ea6acb1abc0c3b89008ee",
        "sha256": "e539199dea6fb8ce0c44e83c419ecd4d15ffd4ba4648938f2e96a924173a36d7"
      },
      {
        "key": "chunks/0d6da06323f18e5d6eb6db9124a982701d10c8620b176ef1afb3f2c159722167/1",
        "size": 1265754,
        "md5": "716cd82263f82f635e7a8263526d3f33",
        "sha256": "0bb9197e4da3db9cde7b840fd54e3ea65693e7e7ffccc776fbed9ef63c014a61"
      }
    ]
  },
  "runtime/mythroad_res/gltzj/resourcefile.res": {
    "version": 1,
    "size": 2416390,
    "md5": "7349b6d573b2a68b1c08c043e26aa153",
    "sha256": "295aa9fd299b1e8e40593a78f4664e7ba7ffa52f61731f8c76afddb9ed0b1092",
    "parts": [
      {
        "key": "chunks/295aa9fd299b1e8e40593a78f4664e7ba7ffa52f61731f8c76afddb9ed0b1092/0",
        "size": 1900000,
        "md5": "80696de10551c49dc99b85fc4a2bcc4b",
        "sha256": "477fb050e039768ba15590b5293e0439bf07c8f909bd5595154fde6c1294d46c"
      },
      {
        "key": "chunks/295aa9fd299b1e8e40593a78f4664e7ba7ffa52f61731f8c76afddb9ed0b1092/1",
        "size": 516390,
        "md5": "0217165df057389e6889dc70742e5be9",
        "sha256": "397694ce9298cf5f80867368cc79dee42b2027e8deb4c2f6691f6939be381643"
      }
    ]
  },
  "runtime/mythroad_res/gkxct/resourcefile.res": {
    "version": 1,
    "size": 3044162,
    "md5": "7ca27340c6a54750f6f38d1a24167923",
    "sha256": "cb232198d73d1bf4154b0ca3cf693f23150461da395437ec9675b2338206a5c5",
    "parts": [
      {
        "key": "chunks/cb232198d73d1bf4154b0ca3cf693f23150461da395437ec9675b2338206a5c5/0",
        "size": 1900000,
        "md5": "0bc52611ad28e31710cf4dea6b3debe3",
        "sha256": "4656c4b48ab3bbff7af436ecfdbc815305693258d95d21396c143fc704e59ccb"
      },
      {
        "key": "chunks/cb232198d73d1bf4154b0ca3cf693f23150461da395437ec9675b2338206a5c5/1",
        "size": 1144162,
        "md5": "1a94ea322471919394f715adc1abc65e",
        "sha256": "767a0340ae73d37840c0441d8a3c4976024f114a3bea08dc42a68a1fece75242"
      }
    ]
  },
  "runtime/mythroad_res/gmhxyb/resourcefile.res": {
    "version": 1,
    "size": 2396704,
    "md5": "e5c094ddd4d60ddfa275a6e6fb19e08a",
    "sha256": "5da4b0cb5d7d60447cff111d44f1cb980e3b02d96b919f3fa2d4c763533fffd2",
    "parts": [
      {
        "key": "chunks/5da4b0cb5d7d60447cff111d44f1cb980e3b02d96b919f3fa2d4c763533fffd2/0",
        "size": 1900000,
        "md5": "436845a97d9e81de53ccaec2d3d0eb93",
        "sha256": "27079f938f40a22dc1755b6d7d28b9940ac4aa9061090dc4c5b8b1006d007cb4"
      },
      {
        "key": "chunks/5da4b0cb5d7d60447cff111d44f1cb980e3b02d96b919f3fa2d4c763533fffd2/1",
        "size": 496704,
        "md5": "c83295600aebac5a4f364670e8dc2606",
        "sha256": "4c5f0e563e5e433ee85b52ad80a84dddda87c3dda6fb9311c4bac39d1ecea401"
      }
    ]
  },
  "runtime/mythroad_res/gmjws/resourcefile.res": {
    "version": 1,
    "size": 2634998,
    "md5": "28189cfe4f61a830599bfb4bab3d74c5",
    "sha256": "f48c255973190a5be5b5a04742b7f095d71786c759b1a90018ad9e8b9ad4cc5c",
    "parts": [
      {
        "key": "chunks/f48c255973190a5be5b5a04742b7f095d71786c759b1a90018ad9e8b9ad4cc5c/0",
        "size": 1900000,
        "md5": "63622c15b877c41ba24de05dcb5b59f8",
        "sha256": "b2bf3f165a377d3f2a86983fa83284cf60101f74cb77dd5992e9b624975aaba8"
      },
      {
        "key": "chunks/f48c255973190a5be5b5a04742b7f095d71786c759b1a90018ad9e8b9ad4cc5c/1",
        "size": 734998,
        "md5": "f235a439b504774ce8f6f89db80cb809",
        "sha256": "7c5ee69214296a29dd5316f8414a267e616d3477bd73a5247955de0d90623ccf"
      }
    ]
  },
  "runtime/mythroad_res/gmyqy/resourcefile.res": {
    "version": 1,
    "size": 2992272,
    "md5": "2caeacb1b272eab87f49b1d9c28dc3fc",
    "sha256": "ead66c632758f15b789303daf5de261e0ce1d4a4897773d15e2c229b7b47cde4",
    "parts": [
      {
        "key": "chunks/ead66c632758f15b789303daf5de261e0ce1d4a4897773d15e2c229b7b47cde4/0",
        "size": 1900000,
        "md5": "b3ce914cc3d28ba391ed311a3d15341e",
        "sha256": "847d04ee5ac305b52e89f776395685cc165641d37a44845f7119f135c92a2678"
      },
      {
        "key": "chunks/ead66c632758f15b789303daf5de261e0ce1d4a4897773d15e2c229b7b47cde4/1",
        "size": 1092272,
        "md5": "b83524c6f2538b5abd5c25c4585af1fc",
        "sha256": "03ad358f621bc79cea80942bd1c0b64ce95813a8a8b0d421edd5f7b65996ece8"
      }
    ]
  },
  "runtime/mythroad_res/gtbmj/resourcefile.res": {
    "version": 1,
    "size": 2155288,
    "md5": "3cffb0b074053a5be903df71fc14be4d",
    "sha256": "f231d87f5850d38832f5bb9a1b4e4add8833c148c33492cb218e37e082589249",
    "parts": [
      {
        "key": "chunks/f231d87f5850d38832f5bb9a1b4e4add8833c148c33492cb218e37e082589249/0",
        "size": 1900000,
        "md5": "74683279e13a4e94ae6af0dc43798ce5",
        "sha256": "a1bc62b5acff1c4b78af50de0d08e1cb923458d4f1ca1d92e2e7de252c34e1eb"
      },
      {
        "key": "chunks/f231d87f5850d38832f5bb9a1b4e4add8833c148c33492cb218e37e082589249/1",
        "size": 255288,
        "md5": "3838044ae7e131cb3343214064a70ace",
        "sha256": "7a048ca8f7ba1d2a6639d85e9025b61780c7d4c78ee318a32a9756907130af65"
      }
    ]
  },
  "runtime/mythroad_res/gxyzs/resourcefile.res": {
    "version": 1,
    "size": 2303264,
    "md5": "a5fabbd6cf8fbb1542c782b1f873c668",
    "sha256": "87a27fe03f007081c90d95f740516e66ca7c526f2cc13bd58819db29843567ab",
    "parts": [
      {
        "key": "chunks/87a27fe03f007081c90d95f740516e66ca7c526f2cc13bd58819db29843567ab/0",
        "size": 1900000,
        "md5": "192df7a4731a8e4808208a159a1aebcf",
        "sha256": "f4cd7b5083a3ebb9c0df11272f3c0f4c2abe9629c13f596232c22651d355df43"
      },
      {
        "key": "chunks/87a27fe03f007081c90d95f740516e66ca7c526f2cc13bd58819db29843567ab/1",
        "size": 403264,
        "md5": "d6e5b74d3433d3e2ad1fb69f4a498916",
        "sha256": "0b1aad8726d1ed382e21ca1ff8a5ff185e0cacedc1b6fc72b4cc47bbe44f66be"
      }
    ]
  },
  "runtime/mythroad_res/gysdbz/vpack": {
    "version": 1,
    "size": 2682189,
    "md5": "d6b390340835a5ff7372f4c326637f05",
    "sha256": "f6bba614e92ef23c12c189cab27dd6111519df13e47a0e88d6adb82416f5059c",
    "parts": [
      {
        "key": "chunks/f6bba614e92ef23c12c189cab27dd6111519df13e47a0e88d6adb82416f5059c/0",
        "size": 1900000,
        "md5": "7eac212491454f6332e832e17f783fcc",
        "sha256": "2d78dd4fa40009162373f36e5445a8f58eed21992a23f22b9e2d3844ee640ba4"
      },
      {
        "key": "chunks/f6bba614e92ef23c12c189cab27dd6111519df13e47a0e88d6adb82416f5059c/1",
        "size": 782189,
        "md5": "cf370fdf29c3f2f8dd53d4b276a5eb51",
        "sha256": "af62fedb757d187d6f740378fb618a3e93c3c8b57c020a5ce465c1d0b8d9e79e"
      }
    ]
  },
  "runtime/mythroad_res/system/gb16.uc2": {
    "version": 1,
    "size": 2097152,
    "md5": "f21f21559a38f8927597cc2088525072",
    "sha256": "6a6d819025765b4b967aa9dd5c7efc5c86b06265b73a14db91869b22bf3d2dd5",
    "parts": [
      {
        "key": "chunks/6a6d819025765b4b967aa9dd5c7efc5c86b06265b73a14db91869b22bf3d2dd5/0",
        "size": 1900000,
        "md5": "9070adf4ee867cb8e5c55cffc60b54db",
        "sha256": "b14858dcb24c648440f37d902b20495b7ab229be5b1000c3495cae53d15d2f5a"
      },
      {
        "key": "chunks/6a6d819025765b4b967aa9dd5c7efc5c86b06265b73a14db91869b22bf3d2dd5/1",
        "size": 197152,
        "md5": "50fe05f61dd9f6541ab2ec6f950d487a",
        "sha256": "ecf34c4f00148618f0a4e5ffb0a6e5aba1c876d675d4d0b82764256c11cb9268"
      }
    ]
  },
  "runtime/mythroad_res/system/gb16_mrpoid.uc2": {
    "version": 1,
    "size": 2097152,
    "md5": "2180f7f403808a9fbe99560001d996ad",
    "sha256": "127d4b969b2e9385f3611b6eb9f7c1b72191b70dedb7b21cd0417f76ae368308",
    "parts": [
      {
        "key": "chunks/127d4b969b2e9385f3611b6eb9f7c1b72191b70dedb7b21cd0417f76ae368308/0",
        "size": 1900000,
        "md5": "77099bedf804fbe052662fce545366f2",
        "sha256": "6a1d0f013bb665dd5dbaff2c7f6f067209361aadf887901105223eb87681ee6f"
      },
      {
        "key": "chunks/127d4b969b2e9385f3611b6eb9f7c1b72191b70dedb7b21cd0417f76ae368308/1",
        "size": 197152,
        "md5": "c9f53567cc684d8f0196970c6be8ffee",
        "sha256": "c75fb24276dc5d9b92e7f51cd13a45e1458e8f24621631d94e5b475f126139ca"
      }
    ]
  },
  "runtime/system/gb16.uc2": {
    "version": 1,
    "size": 2097152,
    "md5": "f21f21559a38f8927597cc2088525072",
    "sha256": "6a6d819025765b4b967aa9dd5c7efc5c86b06265b73a14db91869b22bf3d2dd5",
    "parts": [
      {
        "key": "chunks/6a6d819025765b4b967aa9dd5c7efc5c86b06265b73a14db91869b22bf3d2dd5/0",
        "size": 1900000,
        "md5": "9070adf4ee867cb8e5c55cffc60b54db",
        "sha256": "b14858dcb24c648440f37d902b20495b7ab229be5b1000c3495cae53d15d2f5a"
      },
      {
        "key": "chunks/6a6d819025765b4b967aa9dd5c7efc5c86b06265b73a14db91869b22bf3d2dd5/1",
        "size": 197152,
        "md5": "50fe05f61dd9f6541ab2ec6f950d487a",
        "sha256": "ecf34c4f00148618f0a4e5ffb0a6e5aba1c876d675d4d0b82764256c11cb9268"
      }
    ]
  },
  "runtime/system/gb16_mrpoid.uc2": {
    "version": 1,
    "size": 2097152,
    "md5": "2180f7f403808a9fbe99560001d996ad",
    "sha256": "127d4b969b2e9385f3611b6eb9f7c1b72191b70dedb7b21cd0417f76ae368308",
    "parts": [
      {
        "key": "chunks/127d4b969b2e9385f3611b6eb9f7c1b72191b70dedb7b21cd0417f76ae368308/0",
        "size": 1900000,
        "md5": "77099bedf804fbe052662fce545366f2",
        "sha256": "6a1d0f013bb665dd5dbaff2c7f6f067209361aadf887901105223eb87681ee6f"
      },
      {
        "key": "chunks/127d4b969b2e9385f3611b6eb9f7c1b72191b70dedb7b21cd0417f76ae368308/1",
        "size": 197152,
        "md5": "c9f53567cc684d8f0196970c6be8ffee",
        "sha256": "c75fb24276dc5d9b92e7f51cd13a45e1458e8f24621631d94e5b475f126139ca"
      }
    ]
  },
  "runtime/mythroad_res/system/font16_t.unf": {
    "version": 1,
    "size": 7108100,
    "md5": "cc9f93fdf74e7329acfbb749a5acdd66",
    "sha256": "8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645",
    "parts": [
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/0",
        "size": 1900000,
        "md5": "e601c312f69f242e27990706aac0fd0e",
        "sha256": "f46ee21613cff5201e3d165d449fcc012c2e718cabcbcb43b9092e7a8d3d9955"
      },
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/1",
        "size": 1900000,
        "md5": "67cae222d52468601402883300e967b5",
        "sha256": "3f266127b7541737e814c9c75e3865d81e286274b1bbf8074ec9a112f6aa9ed2"
      },
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/2",
        "size": 1900000,
        "md5": "e3f767ad211fffd3c3e818cf9f68e5ab",
        "sha256": "090006d8166bfe5fc993e9e015197d4ffb1e4c9101438d63d134efb4972389b7"
      },
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/3",
        "size": 1408100,
        "md5": "9e02e98a4f6bad96171afb7b9212d96f",
        "sha256": "2182f2a4d590f2ef9e0212ac04969878404f3243c1745245ba707c381bf89793"
      }
    ]
  },
  "runtime/system/font16_t.unf": {
    "version": 1,
    "size": 7108100,
    "md5": "cc9f93fdf74e7329acfbb749a5acdd66",
    "sha256": "8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645",
    "parts": [
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/0",
        "size": 1900000,
        "md5": "e601c312f69f242e27990706aac0fd0e",
        "sha256": "f46ee21613cff5201e3d165d449fcc012c2e718cabcbcb43b9092e7a8d3d9955"
      },
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/1",
        "size": 1900000,
        "md5": "67cae222d52468601402883300e967b5",
        "sha256": "3f266127b7541737e814c9c75e3865d81e286274b1bbf8074ec9a112f6aa9ed2"
      },
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/2",
        "size": 1900000,
        "md5": "e3f767ad211fffd3c3e818cf9f68e5ab",
        "sha256": "090006d8166bfe5fc993e9e015197d4ffb1e4c9101438d63d134efb4972389b7"
      },
      {
        "key": "chunks/8a634038ceb253a35887c99117d78cc7b6bf8784a5d5b685c64362569278b645/3",
        "size": 1408100,
        "md5": "9e02e98a4f6bad96171afb7b9212d96f",
        "sha256": "2182f2a4d590f2ef9e0212ac04969878404f3243c1745245ba707c381bf89793"
      }
    ]
  }
};
